name:                elm-haskell-template 
version:             0.1.0.0
github:              "https://github.com/nwaywood/elm-haskell-template"
license:             MIT 
author:              "Nick Waywood"
maintainer:          "example@example.com"
copyright:           "2020 Nick Waywood"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/nwaywood/elm-haskell-template#readme

dependencies:
- base >= 4.7 && < 5
- scotty
- wai-middleware-static 
- req
- aeson
- text
- http-types

library:
  source-dirs: src

executables:
  myproj-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-haskell-template 

tests:
  myproj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-haskell-template 
